import type { Exercise } from '../types';

export const EXERCISES: Exercise[] = [
  // Bodyweight
  {
    id: 'push-up',
    name: 'Push-Up',
    category: 'bodyweight',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Start in a plank position with hands shoulder-width apart.',
      'Lower your chest toward the floor, keeping elbows at 45°.',
      'Push back up to the starting position.',
      'Keep your core tight throughout.',
    ],
  },
  {
    id: 'squat',
    name: 'Bodyweight Squat',
    category: 'bodyweight',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Stand with feet shoulder-width apart, toes slightly out.',
      'Push hips back and bend knees, lowering until thighs are parallel to the floor.',
      'Drive through heels to return to standing.',
      'Keep chest up and back straight.',
    ],
  },
  {
    id: 'pull-up',
    name: 'Pull-Up',
    category: 'bodyweight',
    muscleGroups: ['back', 'biceps'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Hang from a bar with hands slightly wider than shoulder-width, palms facing away.',
      'Pull yourself up until your chin clears the bar.',
      'Lower slowly back to a full hang.',
      'Avoid swinging or kipping.',
    ],
  },
  {
    id: 'dip',
    name: 'Tricep Dip',
    category: 'bodyweight',
    muscleGroups: ['triceps', 'chest', 'shoulders'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Place hands on parallel bars or a chair edge, arms straight.',
      'Lower your body by bending elbows to ~90°.',
      'Push back up to the starting position.',
      'Keep elbows close to your body.',
    ],
  },
  {
    id: 'plank',
    name: 'Plank',
    category: 'bodyweight',
    muscleGroups: ['core', 'shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Forearms on the floor, elbows under shoulders.',
      'Body forms a straight line from head to heels.',
      'Brace your core and hold.',
      'Breathe steadily.',
    ],
  },
  {
    id: 'lunge',
    name: 'Forward Lunge',
    category: 'bodyweight',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Stand upright, step forward with one leg.',
      'Lower hips until both knees are ~90°.',
      'Front knee stays over the ankle.',
      'Push off the front foot to return, then alternate.',
    ],
  },
  {
    id: 'burpee',
    name: 'Burpee',
    category: 'bodyweight',
    muscleGroups: ['full_body'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Stand, then squat and place hands on the floor.',
      'Jump feet back to a plank.',
      'Perform a push-up.',
      'Jump feet toward hands, then explosively jump up with arms overhead.',
    ],
  },
  {
    id: 'mountain-climber',
    name: 'Mountain Climber',
    category: 'bodyweight',
    muscleGroups: ['core', 'shoulders', 'hip_flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Start in a high plank position.',
      'Drive one knee toward your chest, then quickly switch legs.',
      'Keep hips level and core tight.',
      'Maintain a steady rhythm.',
    ],
  },
  {
    id: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'bodyweight',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Lie on your back, knees bent, feet flat on the floor.',
      'Drive hips up by squeezing glutes.',
      'Hold at the top for a second.',
      'Lower slowly.',
    ],
  },
  {
    id: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'bodyweight',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'Start in a downward dog position.',
      'Bend elbows to lower the top of your head toward the floor.',
      'Push back up.',
      'Keep hips high throughout.',
    ],
  },
  // Dumbbell exercises
  {
    id: 'db-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Lie on a bench holding dumbbells at chest level.',
      'Press dumbbells up until arms are extended.',
      'Lower slowly back to the starting position.',
      'Keep feet flat on the floor.',
    ],
  },
  {
    id: 'db-row',
    name: 'Dumbbell Row',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Place one knee and hand on a bench for support.',
      'Hold a dumbbell in the other hand, arm extended.',
      'Row the dumbbell to your hip, elbow driving back.',
      'Lower slowly and repeat.',
    ],
  },
  {
    id: 'db-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'strength',
    muscleGroups: ['shoulders', 'triceps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Sit or stand holding dumbbells at shoulder height.',
      'Press dumbbells overhead until arms are fully extended.',
      'Lower to starting position.',
      'Avoid arching your lower back.',
    ],
  },
  {
    id: 'db-curl',
    name: 'Dumbbell Curl',
    category: 'strength',
    muscleGroups: ['biceps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Stand holding dumbbells at your sides, palms facing forward.',
      'Curl dumbbells toward shoulders by bending elbows.',
      'Lower slowly.',
      'Keep elbows tucked at your sides.',
    ],
  },
  {
    id: 'db-goblet-squat',
    name: 'Goblet Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'core'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Hold a dumbbell vertically at chest height.',
      'Squat down keeping the dumbbell close to your chest.',
      'Drive through heels to stand.',
      'Keep chest tall throughout.',
    ],
  },
  {
    id: 'db-rdl',
    name: 'Romanian Deadlift',
    category: 'strength',
    muscleGroups: ['hamstrings', 'glutes', 'lower_back'],
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
    instructions: [
      'Stand holding dumbbells in front of thighs.',
      'Hinge at hips, pushing them back while lowering dumbbells along legs.',
      'Feel a stretch in hamstrings, then drive hips forward to stand.',
      'Keep back flat and core braced.',
    ],
  },
  {
    id: 'db-lateral-raise',
    name: 'Lateral Raise',
    category: 'strength',
    muscleGroups: ['shoulders'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Stand holding dumbbells at your sides.',
      'Raise arms out to shoulder height, slight bend in elbows.',
      'Lower slowly.',
      'Lead with elbows, not hands.',
    ],
  },
  {
    id: 'db-tricep-extension',
    name: 'Tricep Overhead Extension',
    category: 'strength',
    muscleGroups: ['triceps'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Hold one dumbbell overhead with both hands.',
      'Lower behind your head by bending elbows.',
      'Extend back to the top.',
      'Keep upper arms stationary.',
    ],
  },
  {
    id: 'db-lunge',
    name: 'Dumbbell Lunge',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['dumbbells'],
    difficulty: 'beginner',
    instructions: [
      'Hold dumbbells at your sides.',
      'Step forward and lower into a lunge.',
      'Push off the front foot to return.',
      'Alternate legs each rep.',
    ],
  },
  {
    id: 'db-chest-fly',
    name: 'Dumbbell Chest Fly',
    category: 'strength',
    muscleGroups: ['chest'],
    equipment: ['dumbbells'],
    difficulty: 'intermediate',
    instructions: [
      'Lie on a bench holding dumbbells above your chest, slight bend in elbows.',
      'Open arms wide, lowering dumbbells to shoulder height.',
      'Squeeze chest to bring dumbbells back together.',
      'Control the descent.',
    ],
  },
  // Barbell exercises
  {
    id: 'barbell-squat',
    name: 'Barbell Back Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Place barbell on upper traps, feet shoulder-width apart.',
      'Squat down until thighs are at least parallel to the floor.',
      'Drive through heels to stand.',
      'Keep chest up and knees tracking over toes.',
    ],
  },
  {
    id: 'barbell-deadlift',
    name: 'Conventional Deadlift',
    category: 'strength',
    muscleGroups: ['hamstrings', 'glutes', 'back', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Stand with feet hip-width, bar over mid-foot.',
      'Hinge down and grip the bar just outside your legs.',
      'Brace core and pull the bar up by driving hips forward.',
      'Lower the bar with control.',
    ],
  },
  {
    id: 'barbell-bench-press',
    name: 'Barbell Bench Press',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Lie on a bench, grip bar slightly wider than shoulder-width.',
      'Unrack and lower bar to mid-chest.',
      'Press explosively back up.',
      'Keep feet flat and back slightly arched.',
    ],
  },
  {
    id: 'barbell-row',
    name: 'Barbell Row',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Hinge forward ~45°, holding bar at arm's length.',
      'Row the bar to your lower chest.',
      'Lower with control.',
      'Keep back flat and core tight.',
    ],
  },
  {
    id: 'barbell-overhead-press',
    name: 'Overhead Press',
    category: 'strength',
    muscleGroups: ['shoulders', 'triceps', 'core'],
    equipment: ['barbell'],
    difficulty: 'intermediate',
    instructions: [
      'Stand holding bar at shoulder height, elbows forward.',
      'Press bar overhead until arms are locked out.',
      'Lower to start.',
      'Keep core braced and glutes tight.',
    ],
  },
  // Cardio
  {
    id: 'running',
    name: 'Running',
    category: 'cardio',
    muscleGroups: ['legs', 'core', 'cardiovascular'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Start at a comfortable pace.',
      'Land mid-foot, not on heels.',
      'Arms swing naturally at your sides.',
      'Breathe rhythmically.',
    ],
  },
  {
    id: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardiovascular'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Stand with feet together, arms at sides.',
      'Jump feet out wide while raising arms overhead.',
      'Jump back to start.',
      'Keep a steady rhythm.',
    ],
  },
  {
    id: 'jump-rope',
    name: 'Jump Rope',
    category: 'cardio',
    muscleGroups: ['calves', 'cardiovascular'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Hold rope handles at hip height.',
      'Swing the rope overhead and jump as it passes under feet.',
      'Land softly on the balls of your feet.',
      'Keep jumps small.',
    ],
  },
  {
    id: 'high-knees',
    name: 'High Knees',
    category: 'cardio',
    muscleGroups: ['hip_flexors', 'core', 'cardiovascular'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Run in place, driving knees up to hip height.',
      'Pump arms in opposition.',
      'Stay on balls of feet.',
      'Maintain a fast rhythm.',
    ],
  },
  // Flexibility
  {
    id: 'hip-flexor-stretch',
    name: 'Hip Flexor Stretch',
    category: 'flexibility',
    muscleGroups: ['hip_flexors'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Kneel on one knee, other foot forward.',
      'Push hips forward until you feel a stretch in the front of the kneeling hip.',
      'Hold 30 seconds.',
      'Switch sides.',
    ],
  },
  {
    id: 'hamstring-stretch',
    name: 'Hamstring Stretch',
    category: 'flexibility',
    muscleGroups: ['hamstrings'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Sit on the floor with legs extended.',
      'Reach forward toward your feet.',
      'Hold at point of mild tension.',
      'Hold 30-60 seconds.',
    ],
  },
  {
    id: 'chest-stretch',
    name: 'Chest Doorway Stretch',
    category: 'flexibility',
    muscleGroups: ['chest', 'shoulders'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Stand in a doorway, forearms on the frame.',
      'Step forward until you feel a stretch across your chest.',
      'Hold 30 seconds.',
    ],
  },
  {
    id: 'cat-cow',
    name: 'Cat-Cow Stretch',
    category: 'flexibility',
    muscleGroups: ['spine', 'core'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Start on hands and knees.',
      'Arch your back up (cat), tucking chin and pelvis.',
      'Then dip your belly down (cow), lifting head and tailbone.',
      'Flow between positions smoothly.',
    ],
  },
  {
    id: 'pigeon-pose',
    name: 'Pigeon Pose',
    category: 'flexibility',
    muscleGroups: ['glutes', 'hip_flexors'],
    equipment: ['none'],
    difficulty: 'intermediate',
    instructions: [
      'From a plank, bring one knee forward toward the same-side hand.',
      'Lower hips toward the floor.',
      'Lean forward to deepen the stretch.',
      'Hold 60 seconds, then switch.',
    ],
  },
  // Resistance bands
  {
    id: 'band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'strength',
    muscleGroups: ['shoulders', 'upper_back'],
    equipment: ['resistance_bands'],
    difficulty: 'beginner',
    instructions: [
      'Hold a resistance band with both hands, arms extended at shoulder height.',
      'Pull the band apart by squeezing shoulder blades together.',
      'Return slowly.',
      'Keep arms straight throughout.',
    ],
  },
  {
    id: 'band-squat',
    name: 'Banded Squat',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['resistance_bands'],
    difficulty: 'beginner',
    instructions: [
      'Stand on the band with feet shoulder-width apart, holding the ends at shoulder height.',
      'Squat down to parallel.',
      'Drive through heels to stand.',
      'Keep band tension throughout.',
    ],
  },
  {
    id: 'band-bicep-curl',
    name: 'Banded Bicep Curl',
    category: 'strength',
    muscleGroups: ['biceps'],
    equipment: ['resistance_bands'],
    difficulty: 'beginner',
    instructions: [
      'Stand on the band, grip ends at sides.',
      'Curl hands toward shoulders.',
      'Lower slowly.',
      'Keep elbows at sides.',
    ],
  },
  // Full gym
  {
    id: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Sit at a lat pulldown machine, grip bar wider than shoulder-width.',
      'Pull bar to upper chest, squeezing lats.',
      'Return slowly to full extension.',
      'Avoid swinging your torso.',
    ],
  },
  {
    id: 'cable-row',
    name: 'Seated Cable Row',
    category: 'strength',
    muscleGroups: ['back', 'biceps'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Sit at cable row machine with feet on platform.',
      'Pull handle to lower abdomen, squeezing shoulder blades.',
      'Return with control.',
      'Keep torso upright.',
    ],
  },
  {
    id: 'leg-press',
    name: 'Leg Press',
    category: 'strength',
    muscleGroups: ['quadriceps', 'glutes', 'hamstrings'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Sit in leg press machine, feet shoulder-width on platform.',
      'Lower the platform until knees are at 90°.',
      'Press back up without locking knees.',
      'Do not let lower back lift off the seat.',
    ],
  },
  {
    id: 'chest-press-machine',
    name: 'Chest Press Machine',
    category: 'strength',
    muscleGroups: ['chest', 'shoulders', 'triceps'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Adjust seat so handles are at chest height.',
      'Press handles forward until arms are extended.',
      'Return slowly.',
      'Keep back against the pad.',
    ],
  },
  {
    id: 'treadmill-walk',
    name: 'Treadmill Walk',
    category: 'cardio',
    muscleGroups: ['legs', 'cardiovascular'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Set an incline of 2-5% for best results.',
      'Walk at a brisk pace (3-4 mph).',
      'Avoid holding the rails.',
      'Maintain upright posture.',
    ],
  },
  {
    id: 'elliptical',
    name: 'Elliptical Trainer',
    category: 'cardio',
    muscleGroups: ['full_body', 'cardiovascular'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Set resistance and incline to comfortable level.',
      'Push and pull the handles to engage upper body.',
      'Keep an upright posture.',
      'Aim for 130-150 BPM heart rate for moderate intensity.',
    ],
  },
  {
    id: 'hip-thrust-machine',
    name: 'Hip Thrust',
    category: 'strength',
    muscleGroups: ['glutes', 'hamstrings'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Sit on the floor with upper back against a bench, barbell or pad across hips.',
      'Drive hips up by squeezing glutes.',
      'Hold at top, then lower.',
      'Feet flat on the floor, knees at 90° at the top.',
    ],
  },
  {
    id: 'face-pull',
    name: 'Face Pull',
    category: 'strength',
    muscleGroups: ['shoulders', 'upper_back'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Attach rope to cable at head height.',
      'Pull rope toward your face, elbows flaring out.',
      'Squeeze shoulder blades at the end.',
      'Return with control.',
    ],
  },
  {
    id: 'tricep-pushdown',
    name: 'Tricep Pushdown',
    category: 'strength',
    muscleGroups: ['triceps'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Stand at cable machine, grip bar or rope at chest height.',
      'Push down until arms are fully extended.',
      'Return slowly.',
      'Keep elbows at your sides.',
    ],
  },
  {
    id: 'leg-curl',
    name: 'Leg Curl',
    category: 'strength',
    muscleGroups: ['hamstrings'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Lie face-down on the leg curl machine.',
      'Curl legs toward glutes.',
      'Lower slowly.',
      'Avoid lifting your hips.',
    ],
  },
  {
    id: 'leg-extension',
    name: 'Leg Extension',
    category: 'strength',
    muscleGroups: ['quadriceps'],
    equipment: ['full_gym'],
    difficulty: 'beginner',
    instructions: [
      'Sit in leg extension machine, pad on lower shins.',
      'Extend legs to full extension.',
      'Lower slowly.',
      'Avoid locking out knees too forcefully.',
    ],
  },
  {
    id: 'calf-raise',
    name: 'Standing Calf Raise',
    category: 'strength',
    muscleGroups: ['calves'],
    equipment: ['none'],
    difficulty: 'beginner',
    instructions: [
      'Stand with feet hip-width, toes on the edge of a step.',
      'Rise up on your tiptoes.',
      'Lower heels below the step level.',
      'Can use dumbbells or a machine for added resistance.',
    ],
  },
];
