import React from 'react';
import { ScrollView, Text, View, StyleSheet } from 'react-native';
import { SafeView } from '../../components/common/SafeView';
import { useTheme } from '../../hooks/useTheme';
import { useTranslation } from 'react-i18next';

const SECTIONS = [
  {
    title: '1. Acceptance of Terms',
    body: 'By downloading, installing, or using FitAI Coach, you agree to these Terms of Service. If you do not agree, do not use the app.',
  },
  {
    title: '2. Health & Medical Disclaimer',
    body: 'FitAI Coach is for informational and educational purposes only. The AI coaching feature provides general fitness guidance and is NOT a substitute for professional medical advice, diagnosis, or treatment.\n\nAlways consult a qualified healthcare provider before starting any exercise program, especially if you have a medical condition, are pregnant, or have been sedentary for an extended period.\n\nBy using this app, you acknowledge and accept these risks.',
  },
  {
    title: '3. User Responsibilities',
    body: 'You are solely responsible for:\n• The accuracy of information you provide\n• Your workout safety and execution\n• Consulting healthcare professionals as needed\n• Ensuring you are physically able to perform exercises\n• Using the app in compliance with local laws',
  },
  {
    title: '4. Subscriptions & Billing',
    body: 'FitAI Coach offers a free tier and a Premium subscription. Subscriptions are managed through the Apple App Store or Google Play Store via RevenueCat.\n\nSubscriptions automatically renew unless cancelled at least 24 hours before the renewal date. You can manage subscriptions in your device\'s subscription settings.\n\nWe do not offer refunds except as required by law.',
  },
  {
    title: '5. AI-Generated Content',
    body: 'Workout plans and coaching advice are generated by AI. While we strive for quality, AI-generated content may not always be accurate, complete, or appropriate for your specific situation. Always use your judgment and consult professionals.',
  },
  {
    title: '6. Intellectual Property',
    body: 'The app, its content, and features are owned by FitAI Coach and protected by copyright law. You may not copy, modify, or distribute any part of the app without permission.',
  },
  {
    title: '7. Limitation of Liability',
    body: 'To the maximum extent permitted by law, FitAI Coach shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the app, including injury, loss of data, or financial loss.',
  },
  {
    title: '8. Changes to Terms',
    body: 'We may update these terms from time to time. Continued use of the app after changes constitutes acceptance of the new terms.',
  },
  {
    title: '9. Contact',
    body: 'Questions about these terms? Contact us at legal@fitaicoach.com',
  },
];

export function TermsOfServiceScreen() {
  const { colors } = useTheme();
  const { t } = useTranslation();

  return (
    <SafeView edges={['bottom']}>
      <ScrollView contentContainerStyle={styles.container} showsVerticalScrollIndicator={false}>
        <Text style={[styles.lastUpdated, { color: colors.textMuted }]}>{t('terms.lastUpdated')}</Text>

        {SECTIONS.map(({ title, body }) => (
          <View key={title} style={styles.section}>
            <Text style={[styles.sectionTitle, { color: colors.text }]}>{title}</Text>
            <Text style={[styles.body, { color: colors.textSecondary }]}>{body}</Text>
          </View>
        ))}
      </ScrollView>
    </SafeView>
  );
}

const styles = StyleSheet.create({
  container: { padding: 20, gap: 20, paddingBottom: 40 },
  lastUpdated: { fontSize: 12 },
  section: { gap: 8 },
  sectionTitle: { fontSize: 17, fontWeight: '700' },
  body: { fontSize: 14, lineHeight: 22 },
});
